// Chapter 19/reactapp/src/orderDetails.tsx
import { FunctionComponent } from "react";
import { ProductSelectionHelpers as Helpers } from "./data/entities";
import { ProductSelection } from "./data/entities";
import { NavLink } from "react-router-dom";

interface Props {
    selections: ProductSelection[],
    submitCallback: () => void
}

export const OrderDetails: FunctionComponent<Props> = (props) => {
    return <div>
        <h3 className="text-center bg-primary text-white p-2">
            Order Summary
        </h3>
        <div className="p-3">
            <table className="table table-sm table-striped">
                <thead>
                    <tr>
                        <th>Quantity</th><th>Product</th>
                        <th className="text-right">Price</th>
                        <th className="text-right">Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    { props.selections.map(selection => 
                        <tr key={ selection.product.id}>
                            <td> { selection.quantity }</td>
                            <td> { selection.product.name}</td>
                            <td className="text-right">
                                ${ selection.product.price.toFixed(2)}
                            </td>
                            <td className="text-right">
                                ${ Helpers.total([selection]).toFixed(2) }
                            </td>
                        </tr>
                        )}
                </tbody>
                <tfoot>
                    <tr>
                        <th className="text-right" colSpan={3}>Total:</th>
                        <th className="text-right">
                            $ { Helpers.total(props.selections).toFixed(2)}
                        </th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div className="text-center">
            <NavLink to="/products" className="btn btn-secondary m-1">Back</NavLink>
            <button className="btn btn-primary m-1" onClick={ props.submitCallback}>Submit Order</button>
        </div>
    </div>
}

// Chapter 18/angularapp/src/app/orderDetails.component.ts
import { Component } from "@angular/core";
import { Router } from "@angular/router";
import { Order } from "./data/entities";
import { DataSource } from "./data/datasource";

@Component({
    selector: "order-details",
    templateUrl: "./orderDetails.component.ts"
})
export class OrderDetails {
    
    constructor(private dataSource: DataSource, private router: Router) {}

    get order(): Order {
        return this.dataSource.order;
    }

    submit() {
        this.dataSource.storeOrder().subscribe(id => this.router.navigateByUrl(`/summary/${id}`));
    }
}
<h3 class="text-center bg-primary text-white p-2">Order Summary</h3>
<div class="p-3">
    <table class="table table-sm table-striped">
        <thead>
            <tr>
                <th>Quantity</th><th>Product</th>
                <th class="text-end">Price</th>
                <th class="text-end">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let line of order.orderLines">
                <td>{{line.quantity}}</td>
                <td>{{line.product.name}}</td>
                <td class="text-end">
                    ${{line.product.price.toFixed(2)}}
                </td>
                <td class="text-end">${{line.total.toFixed(2)}}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th class="text-end" colspan="3">Total:</th>
                <th class="text-end">${{order.total.toFixed(2)}}</th>
            </tr>
        </tfoot>
    </table>
</div>
<div class="text-center">
    <button class="btn btn-secondary m-1" routerLink="/products">
        Back
    </button>
    <button class="btn btn-primary m-1" (click)="submit()">
        Submit Order
    </button>
</div>
