// Chapter 16/webapp/src/productList.tsx
import { createElement } from "./tools/jsxFactory";
import { Product } from "./data/entities";
import { ProductItem } from "./productItem";
import { CategoryList } from "./categoryList";

export class ProductList {
    props: {
        products: Product[],
        categories: string[],
        selectedCategory: string,
        addToOrderCallback?: (product: Product, quantity: number) => void,
        filterCallback?: (category: string) => void
    }

    getContent(): HTMLElement {
        return <div className="container-fluid">
            <div className="row">
                <div className="col-3 p-2">
                    <CategoryList categories={this.props.categories} selectedCategory={this.props.selectedCategory} callback={this.props.filterCallback} />
                </div>
                <div className="col-9 p-2">
                    {
                        this.props.products.map(p => 
                            <ProductItem product={p} callback={this.props.addToOrderCallback} />)
                    }
                </div>
            </div>
        </div>
    }
}

// Chapter 18/angularapp/src/app/productList.component.ts
import { Component } from "@angular/core";
import { DataSource } from "./data/datasource";
import { Product } from "./data/entities";

@Component({
    selector: "product-list",
    templateUrl: "./productList.component.html"
})
export class ProductList {
    selectedCategory = "All";

    constructor(public dataSource: DataSource) {}

    get products(): Product[] {
        return this.dataSource.getProducts("id", this.selectedCategory === "All" ? undefined : this.selectedCategory);
    }

    get categories(): string[] {
        return ["All", ...this.dataSource.getCategories()];
    }

    handleCategorySelect(category: string) {
        this.selectedCategory = category;
    }

    handleAdd(data: {product: Product, quantity: number}) {
        this.dataSource.order.addProduct(data.product, data.quantity);
    }

    handleSubmit() {
        console.log("SUBMIT");
    }
}
<header [order]="dataSource.order" (submit)="handleSubmit()"></header>
<div class="container-fluid">
    <div class="row">
        <div class="col-3 p-2">
            <category-list [selected]="selectedCategory" [categories]="categories" (selectCategory)="handleCategorySelect($event)"></category-list>
        </div>
        <div class="col-9 p-2">
            <product-item *ngFor="let p of products" [product]="p" (addToCart)="handleAdd($event)"></product-item>
        </div>
    </div>
</div>
