// Chapter 17/webapp/src/summary.tsx
import { createElement } from "./tools/jsxFactory";

export class Summary {

    props: {
        orderId: number,
        callback: () => void
    }

    getContent(): HTMLElement {
        return <div className="m-2 text-center">
            <h2>Thanks!</h2>
            <p>Thanks for placing your order.</p>
            <p>Your order is ${this.props.orderId}</p>
            <p>We'll ship your goods as soon as possible.</p>
            <button className="btn btn-primary" onclick={this.props.callback}>
                OK
            </button>
        </div>
    }
}

// Chapter 18/angularapp/src/app/summary.component.ts
import { Component } from "@angular/core";
import { Router, ActivatedRoute } from "@angular/router";

@Component({
    selector: "summary",
    templateUrl: "./summary.component.html"
})
export class Summary {

    constructor(private activatedRoute: ActivatedRoute) {}

    get id(): string {
        return this.activatedRoute.snapshot.params["id"];
    }
} 
<div class="m-2 text-center">
    <h2>Thanks!</h2>
    <p>Thanks for placing your order.</p>
    <p>Your order is #{{id}}</p>
    <p>We'll ship your goods as soon as possible</p>
    <button class="btn btn-primary" routerLink="/products">OK</button>
</div>
