// Chapter 19/reactapp/src/summary.tsx
import React, { FunctionComponent } from "react";
import { NavLink, useParams } from "react-router-dom";

export const Summary: FunctionComponent = () => {
    const { id } = useParams();

    return <div className="m-2 text-center">
            <h2>Thanks!</h2>
            <p>Thanks for placing your order</p>
            <p>Your order is #{ id }</p>
            <p>We'll ship your goods as soon as possible.</p>
            <NavLink to="/products" className="btn btn-primary">OK</NavLink>
    </div>
}

// Chapter 18/angularapp/src/app/summary.component.ts
import { Component } from "@angular/core";
import { Router, ActivatedRoute } from "@angular/router";

@Component({
    selector: "summary",
    templateUrl: "./summary.component.html"
})
export class Summary {

    constructor(private activatedRoute: ActivatedRoute) {}

    get id(): string {
        return this.activatedRoute.snapshot.params["id"];
    }
} 
<div class="m-2 text-center">
    <h2>Thanks!</h2>
    <p>Thanks for placing your order.</p>
    <p>Your order is #{{id}}</p>
    <p>We'll ship your goods as soon as possible</p>
    <button class="btn btn-primary" routerLink="/products">OK</button>
</div>
