// Chapter 18/angularapp/src/app/productItem.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { Product } from "./data/entities";

export type productSelection = {
    product: Product,
    quantity: number
}

@Component({
    selector: "product-item",
    templateUrl: "./productItem.component.html"
})
export class ProductItem {
    quantity: number = 1;

    @Input()
    product: Product = {
        id: 0, name: "", description: "", category: "", price: 0
    }

    @Output()
    addToCart = new EventEmitter<productSelection>();

    handleAddToCart() {
        this.addToCart.emit({ product: this.product, quantity: Number(this.quantity)});
    }
}
<div class="card m-1 p-1 bg-light">
    <h4>
        {{product.name}}
        <span class="badge rounded-pill bg-primary float-end">
            ${{product.price.toFixed(2)}}
        </span>
    </h4>
    <div class="card-text bg-white p-1">
        {{product.description}}
        <button class="btn btn-success btn-sm float-end" (click)="handleAddToCart()">
            Add To Cart
        </button>
        <select class="form-control-inline float-end m-1" [(ngModel)]="quantity">
            <option>1</option>
            <option>2</option>
            <option>3</option>
        </select>
    </div>
</div>

// Chapter 19/reactapp/src/productItem.tsx
import React, { FunctionComponent, useState } from "react";
import { Product } from "./data/entities";

interface Props {
    product: Product,
    callback: (product: Product, quantity: number) => void
}

// interface State {
//     quantity: number
// }

export const ProductItem: FunctionComponent<Props> = (props) => {

    const [quantity, setQuantity] = useState<number>(1);

    return <div className="card m-1 p-1 bg-light">
        <h4>
            {props.product.name}
            <span className="badge rounded-pill bg-primary float-end">
                ${props.product.price.toFixed(2)}
            </span>
        </h4>
        <div className="card-text bg-white p-1">
            {props.product.description}
            <button className="btn btn-success btn-name float-end" onClick={ () => props.callback(props.product, quantity) } >
                Add To Cart
            </button>
            <select className="form-control-inline float-end m-1" onChange={ (ev) => setQuantity(Number(ev.target.value)) } >
                <option>1</option>
                <option>2</option>
                <option>3</option>
            </select>
        </div>
    </div>
}
