// Chapter 18/angularapp/src/app/productItem.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { Product } from "./data/entities";

export type productSelection = {
    product: Product,
    quantity: number
}

@Component({
    selector: "product-item",
    templateUrl: "./productItem.component.html"
})
export class ProductItem {
    quantity: number = 1;

    @Input()
    product: Product = {
        id: 0, name: "", description: "", category: "", price: 0
    }

    @Output()
    addToCart = new EventEmitter<productSelection>();

    handleAddToCart() {
        this.addToCart.emit({ product: this.product, quantity: Number(this.quantity)});
    }
}
<div class="card m-1 p-1 bg-light">
    <h4>
        {{product.name}}
        <span class="badge rounded-pill bg-primary float-end">
            ${{product.price.toFixed(2)}}
        </span>
    </h4>
    <div class="card-text bg-white p-1">
        {{product.description}}
        <button class="btn btn-success btn-sm float-end" (click)="handleAddToCart()">
            Add To Cart
        </button>
        <select class="form-control-inline float-end m-1" [(ngModel)]="quantity">
            <option>1</option>
            <option>2</option>
            <option>3</option>
        </select>
    </div>
</div>

// Chapter 17/webapp/src/productItem.tsx
import { createElement } from "./tools/jsxFactory";
import { Product } from "./data/entities";

export class ProductItem {
    private quantity: number = 1;

    props: {
        product: Product,
        callback: (product: Product, quantity: number) => void
    }

    getContent(): HTMLElement {
        return <div className="card card-outline-primary m-1 p-1 bg-light">
            <h4>
                { this.props.product.name }
                <span className="badge rounded-pill bg-primary text-white" style="float:right">
                    <small>${this.props.product.price.toFixed(2)}</small>
                </span>
            </h4>
            <div className="card-text bg-white p-1">
                {this.props.product.description}
                <button className="btn btn-success btn-sm float-end" onclick={this.handleAddToCart }>
                    Add to Cart
                </button>
                <select className="form-control-inline float-end m-1" onchange={this.handleQuantityChange }>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                </select>
            </div>
        </div>
    }

    handleQuantityChange = (ev: Event): void => {
        this.quantity = Number((ev.target as HTMLSelectElement).value);
    }

    handleAddToCart = (): void => {
        this.props.callback(this.props.product, this.quantity);
    }
}
